version: "3.9"

services:
  mysql_master:
    image: mysql:latest
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: 'default'
      MYSQL_DATABASE: 'prjctr'
    volumes:
      - mysql-master-data:/var/lib/mysql
      - .infrastructure/mysql.master.cnf:/etc/mysql/conf.d/mysql.conf.cnf

  mysql_slave_1:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'default'
      MYSQL_DATABASE: 'prjctr'
    volumes:
     - mysql-slave-1-data:/var/lib/mysql
     - .infrastructure/mysql.slave-1.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    depends_on:
      - mysql_master

  mysql_slave_2:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'default'
      MYSQL_DATABASE: 'prjctr'
    volumes:
      - mysql-slave-2-data:/var/lib/mysql
      - .infrastructure/mysql.slave-2.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    depends_on:
      - mysql_master

volumes:
  mysql-master-data:
  mysql-slave-1-data:
  mysql-slave-2-data:
